"""
Instance generator for the 15-puzzle.

Instances are generated by performing random walks from the goal state,
which guarantees solvability by construction.

Difficulty is controlled by walk length:
    easy   →  20 – 30  moves  (shallow, fast to solve)
    medium →  35 – 45  moves
    hard   →  50 – 80  moves  (deep; may still vary in true optimal length)

Note: walk length ≠ optimal solution length because random walks can
backtrack.  For rigorous difficulty categorisation you would run an
optimal solver (e.g. IDA* with PDB) to measure true optimal depth.
For the purposes of this project the walk length gives a useful
*approximate* difficulty proxy.
"""

from __future__ import annotations
import random
from typing import Literal

from domain.puzzle import GOAL_STATE, get_neighbors, is_solvable

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

Difficulty = Literal["easy", "medium", "hard"]

WALK_RANGES: dict[Difficulty, tuple[int, int]] = {
    "easy":   (20, 30),
    "medium": (35, 45),
    "hard":   (50, 80),
}

SEED_OFFSETS: dict[Difficulty, int] = {
    "easy": 0,
    "medium": 10_000,
    "hard": 20_000,
}


# ---------------------------------------------------------------------------
# Core generator
# ---------------------------------------------------------------------------

def random_walk(
    start: tuple[int, ...],
    n_steps: int,
    rng: random.Random,
) -> tuple[int, ...]:
    """
    Perform *n_steps* random moves from *start*, avoiding immediate reversal.
    Returns the resulting state.
    """
    state = start
    prev = None
    for _ in range(n_steps):
        neighbours = [nb for nb in get_neighbors(state) if nb != prev]
        if not neighbours:          # shouldn't happen on a 4×4 grid
            neighbours = list(get_neighbors(state))
        prev = state
        state = rng.choice(neighbours)
    return state


def generate_instance(
    difficulty: Difficulty = "medium",
    seed: int | None = None,
) -> tuple[int, ...]:
    """
    Return a single random start state of the requested difficulty.
    The goal state is always GOAL_STATE (tiles 1-15 in order, blank last).
    """
    rng = random.Random(seed)
    lo, hi = WALK_RANGES[difficulty]
    n_steps = rng.randint(lo, hi)
    state = random_walk(GOAL_STATE, n_steps, rng)
    # Sanity check (should always pass since we start from goal)
    assert is_solvable(state), "Generated an unsolvable state — bug in generator"
    return state


def generate_suite(
    n_easy: int = 20,
    n_medium: int = 20,
    n_hard: int = 20,
    base_seed: int = 42,
) -> dict[Difficulty, list[tuple[int, ...]]]:
    """
    Return a dict of difficulty → list of start states.

    Using deterministic seeds makes experiments reproducible.
    """
    suite: dict[Difficulty, list[tuple[int, ...]]] = {
        "easy":   [],
        "medium": [],
        "hard":   [],
    }
    counts = {"easy": n_easy, "medium": n_medium, "hard": n_hard}
    for diff, n in counts.items():
        for i in range(n):
            seed = base_seed + SEED_OFFSETS[diff] + i
            suite[diff].append(generate_instance(diff, seed=seed))  # type: ignore[arg-type]
    return suite
